server:
  port: 8866

spring:
  dubbo:
    application:
      name: server-web
    registry:
      address: zookeeper://127.0.0.1:2181
    protocol:
      name: dubbo
      port: 20881
    consumer:
      check: false
    reference:
        loadbalance: roundrobin #轮询机制
        #loadbalance: random #随机机制
        #loadbalance: leastactive #最少活跃调用数机制
    scan: cn.wellcare